//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSDateTimePlugin\src\main\java\com\ashera\datetime\DatePickerImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_DatePickerImpl")
#ifdef RESTRICT_DatePickerImpl
#define INCLUDE_ALL_DatePickerImpl 0
#else
#define INCLUDE_ALL_DatePickerImpl 1
#endif
#undef RESTRICT_DatePickerImpl

#if !defined (ASDatePickerImpl_) && (INCLUDE_ALL_DatePickerImpl || defined(INCLUDE_ASDatePickerImpl))
#define ASDatePickerImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

#define RESTRICT_FormElement 1
#define INCLUDE_ASFormElement 1
#include "FormElement.h"

@class ASWidgetAttribute;
@class IOSClass;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASDatePickerImpl : ASBaseHasWidgets < ASFormElement >
@property id uiView;
@property id datepicker;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (void)focus;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (NSString *)getTextEntered;

- (IOSClass *)getViewClass;

- (void)initDatePicker OBJC_METHOD_FAMILY_NONE;

- (void)invalidate;

- (jboolean)isViewVisible;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (void)nativeCreateView;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (jboolean)removeWithInt:(jint)index;

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)resetError;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(jboolean)b;

- (void)showErrorWithNSString:(NSString *)message;

#pragma mark Package-Private

@end

J2OBJC_EMPTY_STATIC_INIT(ASDatePickerImpl)

inline NSString *ASDatePickerImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASDatePickerImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASDatePickerImpl, LOCAL_NAME, NSString *)

inline NSString *ASDatePickerImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASDatePickerImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASDatePickerImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASDatePickerImpl_init(ASDatePickerImpl *self);

FOUNDATION_EXPORT ASDatePickerImpl *new_ASDatePickerImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASDatePickerImpl *create_ASDatePickerImpl_init(void);

FOUNDATION_EXPORT void ASDatePickerImpl_initWithNSString_(ASDatePickerImpl *self, NSString *localname);

FOUNDATION_EXPORT ASDatePickerImpl *new_ASDatePickerImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASDatePickerImpl *create_ASDatePickerImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASDatePickerImpl_initWithNSString_withNSString_(ASDatePickerImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASDatePickerImpl *new_ASDatePickerImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASDatePickerImpl *create_ASDatePickerImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASDatePickerImpl)

@compatibility_alias ComAsheraDatetimeDatePickerImpl ASDatePickerImpl;

#endif

#if !defined (ASDatePickerImpl_DatePickerExt_) && (INCLUDE_ALL_DatePickerImpl || defined(INCLUDE_ASDatePickerImpl_DatePickerExt))
#define ASDatePickerImpl_DatePickerExt_

#define RESTRICT_DatePicker 1
#define INCLUDE_ASDatePicker 1
#include "DatePicker.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADRect;
@class ADView;
@class ASDatePickerImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASDatePickerImpl_DatePickerExt : ASDatePicker < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASDatePickerImpl:(ASDatePickerImpl *)outer$;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (jint)getMaxHeight;

- (jint)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(jint)height;

- (void)setMaxWidthWithInt:(jint)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(jint)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASDatePickerImpl_DatePickerExt)

FOUNDATION_EXPORT void ASDatePickerImpl_DatePickerExt_initWithASDatePickerImpl_(ASDatePickerImpl_DatePickerExt *self, ASDatePickerImpl *outer$);

FOUNDATION_EXPORT ASDatePickerImpl_DatePickerExt *new_ASDatePickerImpl_DatePickerExt_initWithASDatePickerImpl_(ASDatePickerImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASDatePickerImpl_DatePickerExt *create_ASDatePickerImpl_DatePickerExt_initWithASDatePickerImpl_(ASDatePickerImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASDatePickerImpl_DatePickerExt)

#endif

#pragma pop_macro("INCLUDE_ALL_DatePickerImpl")
