//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSDateTimePlugin\src\main\java\com\ashera\datetime\TimePickerImpl.java
//

#import <Foundation/Foundation.h>
#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_TimePickerImpl")
#ifdef RESTRICT_TimePickerImpl
#define INCLUDE_ALL_TimePickerImpl 0
#else
#define INCLUDE_ALL_TimePickerImpl 1
#endif
#undef RESTRICT_TimePickerImpl

#if !defined (ASTimePickerImpl_) && (INCLUDE_ALL_TimePickerImpl || defined(INCLUDE_ASTimePickerImpl))
#define ASTimePickerImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

#define RESTRICT_FormElement 1
#define INCLUDE_ASFormElement 1
#include "FormElement.h"

@class ASWidgetAttribute;
@class IOSClass;
@class JavaLangBoolean;
@class JavaLangInteger;
@class NSString;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASTimePickerImpl : ASBaseHasWidgets < ASFormElement >
@property id uiView;
@property id datepicker;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(int32_t)index;

- (id)asNativeWidget;

- (id)asWidget;

- (bool)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (void)focus;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (NSString *)getTextEntered;

- (IOSClass *)getViewClass;

- (void)initTimePicker OBJC_METHOD_FAMILY_NONE;

- (void)invalidate;

- (bool)isViewVisible;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (void)nativeCreateView;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (bool)removeWithInt:(int32_t)index;

- (bool)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)resetError;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(bool)b;

- (void)showErrorWithNSString:(NSString *)message;

#pragma mark Package-Private

@end

J2OBJC_EMPTY_STATIC_INIT(ASTimePickerImpl)

inline NSString *ASTimePickerImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASTimePickerImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASTimePickerImpl, LOCAL_NAME, NSString *)

inline NSString *ASTimePickerImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASTimePickerImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASTimePickerImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASTimePickerImpl_init(ASTimePickerImpl *self);

FOUNDATION_EXPORT ASTimePickerImpl *new_ASTimePickerImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTimePickerImpl *create_ASTimePickerImpl_init(void);

FOUNDATION_EXPORT void ASTimePickerImpl_initWithNSString_(ASTimePickerImpl *self, NSString *localname);

FOUNDATION_EXPORT ASTimePickerImpl *new_ASTimePickerImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTimePickerImpl *create_ASTimePickerImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASTimePickerImpl_initWithNSString_withNSString_(ASTimePickerImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASTimePickerImpl *new_ASTimePickerImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTimePickerImpl *create_ASTimePickerImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASTimePickerImpl)

@compatibility_alias ComAsheraDatetimeTimePickerImpl ASTimePickerImpl;


#endif

#if !defined (ASTimePickerImpl_TimePickerExt_) && (INCLUDE_ALL_TimePickerImpl || defined(INCLUDE_ASTimePickerImpl_TimePickerExt))
#define ASTimePickerImpl_TimePickerExt_

#define RESTRICT_TimePicker 1
#define INCLUDE_ASTimePicker 1
#include "TimePicker.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADRect;
@class ADView;
@class ASTimePickerImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@class JavaLangBoolean;
@class JavaLangInteger;
@class NSString;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASTimePickerImpl_TimePickerExt : ASTimePicker < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASTimePickerImpl:(ASTimePickerImpl *)outer$;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (int32_t)getMaxHeight;

- (int32_t)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(int32_t)offset;

- (void)offsetTopAndBottomWithInt:(int32_t)offset;

- (void)onMeasureWithInt:(int32_t)widthMeasureSpec
                 withInt:(int32_t)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(int32_t)height;

- (void)setMaxWidthWithInt:(int32_t)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(int32_t)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(int32_t)width
                               withInt:(int32_t)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(bool)changed
                    withInt:(int32_t)l
                    withInt:(int32_t)t
                    withInt:(int32_t)r
                    withInt:(int32_t)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTimePickerImpl_TimePickerExt)

FOUNDATION_EXPORT void ASTimePickerImpl_TimePickerExt_initWithASTimePickerImpl_(ASTimePickerImpl_TimePickerExt *self, ASTimePickerImpl *outer$);

FOUNDATION_EXPORT ASTimePickerImpl_TimePickerExt *new_ASTimePickerImpl_TimePickerExt_initWithASTimePickerImpl_(ASTimePickerImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTimePickerImpl_TimePickerExt *create_ASTimePickerImpl_TimePickerExt_initWithASTimePickerImpl_(ASTimePickerImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASTimePickerImpl_TimePickerExt)


#endif

#pragma pop_macro("INCLUDE_ALL_TimePickerImpl")
